
language: php

sudo: required
dist: trusty
group: edge

env:
  global:
    - DEPS=latest

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  include:
    - php: 7
      env:
        - DEPS=lowest
    - php: 7
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.1
    - php: hhvm-3.12
      env:
        - DEPS=lowest
        - HHVMPHP7="yes"
    - php: hhvm-3.12
      env:
        - HHVMPHP7="yes"
    - php: hhvm-3.15
      env:
        - DEPS=lowest
        - HHVMPHP7="yes"
    - php: hhvm-3.15
      env:
        - HHVMPHP7="yes"
    - php: hhvm-nightly
      env:
        - DEPS=lowest
        - HHVMPHP7="yes"
    - php: hhvm-nightly
      env:
        - HHVMPHP7="yes"
    - php: nightly
      env:
        - DEPS=lowest
    - php: nightly
  allow_failures:
    - php: nightly
    - php: hhvm-nightly

before_script:
   - if [[ $HHVMPHP7 == "yes" ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi

install:
 - if [[ $DEPS == 'latest' ]]; then travis_retry composer update -o --prefer-source ; fi
 - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update -o --prefer-lowest --prefer-stable ; fi
 - composer show

script:
 - php ./vendor/bin/phpunit --configuration tests/phpunit.xml
